/* ===============
MOVIES
all numbers and special chars removed
=============== */
const movies = [
  "a beautiful mind",
  "a charlie brown christmas",
  "a christmas story",
  "a quiet place",
  "a star is born",
  "about time",
  "ad astra",
  "alien",
  "always be my maybe",
  "american beauty",
  "anchorman",
  "annihilation",
  "apocalypto",
  "arrival",
  "arthur christmas",
  "avatar",
  "baby driver",
  "back to the future",
  "bad santa",
  "baywatch",
  "beautiful boy",
  "big hero six",
  "bird box",
  "black panther",
  "black swan",
  "black widow",
  "blade runner",
  "blockers",
  "booksmart",
  "boyhood",
  "bridesmaids",
  "bridget jones’s diary",
  "call me by your name",
  "cast away",
  "chicken run",
  "children of men",
  "chinatown",
  "christmas vacation",
  "clueless",
  "collateral",
  "crazy rich asians",
  "crazy, stupid, love",
  "dawn of the dead",
  "despicable me",
  "die hard",
  "die hard",
  "dodgeball",
  "dolittle",
  "dora and the lost city of gold",
  "dumb and dumber",
  "dumbo",
  "edge of tomorrow",
  "edward scissorhands",
  "elf",
  "eyes wide shut",
  "finding dory",
  "forgetting sarah marshall",
  "forrest gump",
  "free guy",
  "frozen",
  "game night",
  "get out",
  "ghost dog",
  "ghostbusters",
  "gifted",
  "gladiator",
  "good boys",
  "goodfellas",
  "gravity",
  "green book",
  "halloween",
  "hancock",
  "happiest season",
  "heat",
  "hereditary",
  "home again",
  "home alone",
  "how the grinch stole christmas!",
  "how to train your dragon",
  "hustlers",
  "i feel pretty",
  "inception",
  "raiders of the lost ark",
  "inside out",
  "insomnia",
  "interstellar",
  "it",
  "it happened on fifth avenue",
  "james bond: casino royale",
  "jaws",
  "john wick",
  "jojo rabbit",
  "joyeux noël",
  "kill bill",
  "kingsman: the secret service",
  "klaus",
  "knives out",
  "knocked up",
  "kong skull island",
  "kung fu panda",
  "last christmas",
  "lethal weapon",
  "liar liar",
  "lion",
  "logan",
  "love actually",
  "love actually",
  "love, simon",
  "lucky number slevin",
  "mad max",
  "mary poppins returns",
  "meet the fockers",
  "minions",
  "minority report",
  "minority report",
  "mission impossible",
  "moana",
  "monsters inc.",
  "moon",
  "moonlight",
  "mother!",
  "mulholland dr.",
  "munich",
  "my spy",
  "mystic river",
  "no country for old men",
  "noelle",
  "notting hill",
  "old school",
  "oldboy",
  "paranormal activity",
  "parasite",
  "predator",
  "pretty woman",
  "prisoners",
  "rango",
  "ready player one",
  "ring",
  "rocky",
  "rudolph, the red-nosed reindeer",
  "run lola run",
  "saving private ryan",
  "scoob!",
  "scream",
  "scrooge",
  "scrooged",
  "seven",
  "shazam!",
  "shrek",
  "shutter island",
  "silent night",
  "sin city",
  "snowpiercer",
  "sonic the hedgehog",
  "sorry to bother you",
  "soul",
  "source code",
  "southpaw",
  "spider-man",
  "split",
  "spotlight",
  "star trek the wrath of khan",
  "star wars the rise of skywalker",
  "step brothers",
  "straw dogs",
  "suicide squad",
  "superbad",
  "tag",
  "taken",
  "taxi driver",
  "tenet",
  "the accountant",
  "the big lebowski",
  "the big sick",
  "the blair witch project",
  "the bourne identity",
  "the cabin in the woods",
  "the christmas chronicles",
  "the conjuring",
  "the dark knight",
  "the departed",
  "the exorcist",
  "the favourite",
  "the fly",
  "the fugitive",
  "the game",
  "the godfather",
  "the green mile",
  "the half of it",
  "the house with a clock in its walls",
  "the human centipede",
  "the incredibles",
  "the invisible man",
  "the lego movie",
  "the lion king",
  "the longshot",
  "the martian",
  "the matrix",
  "the next three days",
  "the nice guys",
  "the night before",
  "the nightmare before christmas",
  "the notebook",
  "the other guys",
  "the others",
  "the peanut butter falcon",
  "the prestige",
  "the proposal",
  "the santa clause",
  "the secret life of pets",
  "the shawshank redemption",
  "the shining",
  "the shop around the corner",
  "the silence of the lambs",
  "the silence of the lambs",
  "the sixth sense",
  "the terminator",
  "the texas chain saw massacre",
  "the thing",
  "the transporter",
  "the usual suspects",
  "the wailing",
  "the witch",
  "there will be blood",
  "there’s something about mary",
  "thor",
  "titanic",
  "togo",
  "tomb raider",
  "total recall",
  "toy story",
  "trading places",
  "trainwreck",
  "trolls",
  "tropic thunder",
  "twelve monkeys",
  "up",
  "us",
  "v for vendetta",
  "vice",
  "wall-e",
  "wedding crashers",
  "when harry met sally",
  "whiplash",
  "wonder",
  "wreck-it ralph",
  "you’ve got mail",
  "zoolander",
];

export default movies;
